name: flutter_news_web
description: A new Flutter project.

dependencies:
  http: "^0.11.3+16"
  flutter:
    sdk: flutter
  flutter_webview_plugin: ^0.3.3
  share: ^0.5.3
  cached_network_image: ^0.7.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
  - images/no_image_available.png
  - images/app_logo.png
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
    - family: Bebes
      fonts: 
        - asset: fonts/BebasNeue-Regular.ttf